// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace UwpSample.Models
{
    internal partial class CurrentAudioInfo
    {
        internal class AudioSetting
        {
            [JsonProperty("paragraphName")]
            public string ParagraphName { get; set; }

            [JsonProperty("startMarker")]
            public string StartMarker { get; set; }

            [JsonProperty("endMarker")]
            public string EndMarker { get; set; }
        }
    }
}
