// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

// http://james.newtonking.com/json

namespace UwpSample.Dtos
{
    internal partial class CurrentAudioInfoDto
    {
        [JsonProperty("audioSettings")]
        public AudioSetting[] AudioSettings { get; set; }
    }
}
